Migrate to typoscript lint aciton
TYPO3-Documentation/tea pull request #220
Opened 2021-03-20 15:20 UTC by lukaszuznanski

2021-03-20 16:41 UTC, oliverklee requested changes
We also need to remove `tools/typo3-typoscript-lint` and remove it from the PHIVE configuration file.

2021-03-20 16:42 UTC, oliverklee commented on .github/workflows/ci.yml
> +      fail-fast: false
This is not needed in this case it this setting does not make any difference for jobs without a matrix.

2021-03-20 17:41 UTC, lukaszuznanski commented
> We also need to remove `tools/typo3-typoscript-lint` and remove it from the PHIVE configuration file.

Maybe we should keep it in phive and in composer.json in order to run lints locally?

2021-03-20 17:49 UTC, oliverklee commented
> Maybe we should keep it in phive and in `composer.json` in order to run lints locally?

I hadn't thought of this … is there any way we can avoid these redundancies? Maybe execute the GitHub actions locally?

2021-03-21 18:51 UTC, lukaszuznanski commented
> > Maybe we should keep it in phive and in `composer.json` in order to run lints locally?
> 
> I hadn't thought of this … is there any way we can avoid these redundancies? Maybe execute the GitHub actions locally?

Right now I found only "nektos/act" tool to running github actions locally, but anyway, removal of phar files and composer.json scripts will break gitlab-ci pipeline.

2021-03-22 11:34 UTC, oliverklee approved these changes

2021-03-22 11:34 UTC, merged