[DOCS] Update docs
TYPO3-Documentation/tea pull request #404
Opened 2022-03-20 15:20 UTC by alexander-nitsche

Hi Oliver, hi Tea team,

this PR is a suggestion to align your extension with the recently introduced [TYPO3 documentation standards](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html).

I transformed your existing rather single file documentation into a full documentation, and split the content into several files. I further reworked some content, most prominently added the full list of composer commands, so that they can be found via the global search at docs.typo3.org.

Greetings, Alex

Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/181

2022-03-23 15:44 UTC, oliverklee requested changes
Thanks for this monumental contribution, @alexander-nitsche! :heart:

As the first review pass, I have added my remarks concerning the documentation structure.

2022-03-23 15:44 UTC, oliverklee commented on README.md
> -# Example TYPO3 extension for code quality checks and automated tests
Please let's keep the main heading the first thing in the document (above the badges).

2022-03-23 15:44 UTC, oliverklee commented on README.md
> +[![TYPO3](https://img.shields.io/badge/TYPO3-10-orange.svg)](https://get.typo3.org/version/10)
Please let's keep the current order of the version badges: from lowest to highest.

2022-03-23 15:44 UTC, oliverklee commented on README.md
> -[![License](https://poser.pugx.org/ttn/tea/license.svg)](https://packagist.org/packages/ttn/tea)
Please don't remove the license badge.

2022-03-29 10:55 UTC, oliverklee commented
@alexander-nitsche Do you have time to update the PR during the next few days, or should someone from the team take over?

2022-03-29 14:28 UTC, alexander-nitsche commented
hi @oliverklee , just go ahead and adapt the PR to your likes. greetings, alex

2022-04-08 07:26 UTC, alexander-nitsche commented
Added two new commits regarding badges in README and additional sources (TER + docs.typo3.org) in composer.json.

In addition, the tea [TER homepage](https://extensions.typo3.org/extension/tea) is missing the "Extension Manual" and "Packagist" buttons, which seem to be caused by an empty "Composer name of extension" field in the TER extension edit form.

2022-04-08 07:28 UTC, alexander-nitsche commented on Documentation/Index.rst
> +----
It's a horizontal line that just looks good, see e.g. https://docs.typo3.org/p/friendsoftypo3/tt-address/main/en-us/.

2022-04-12 16:44 UTC, oliverklee commented on README.md
> +[![TYPO3](https://img.shields.io/badge/TYPO3-10-orange.svg)](https://get.typo3.org/version/10)
Done.

2022-04-12 16:44 UTC, oliverklee commented on README.md
> -[![License](https://poser.pugx.org/ttn/tea/license.svg)](https://packagist.org/packages/ttn/tea)
Done.

2022-04-12 16:45 UTC, oliverklee commented on README.md
> +# TYPO3 extension `tea`
Done.

2022-04-12 16:53 UTC, oliverklee commented on Documentation/ContinuousIntegration/Index.rst
> +.. include:: /Includes.rst.txt
Done.

2022-04-12 16:58 UTC, oliverklee approved these changes
Thanks, Alexander! :heart:

2022-04-12 17:00 UTC, merged