[TASK] Upgrade to Composer 2.4
TYPO3-Documentation/tea pull request #513
Opened 2022-08-23 11:32 UTC by oliverklee

Now that Composer 2.4 has had its first point release, we can safely
upgrade from 2.3 to 2.4 in the DDEV configuration and the CI pipeline.

2022-08-24 11:06 UTC, oliverklee commented
The CI failures are due to the know XLIFF linting problem (schema file not downloadable), and are not related to the changes in this PR.

2022-08-27 15:27 UTC, brotkrueml reviewed
What is the background behind defining the composer version in GitHub actions? The most recent version is used when nothing is defined. Or do you want to update to a new minor version explicitly to avoid possible breakings (which should not occur in minor versions)?

Also, as a cron is configured, this would give early response after that run when an new composer version breaks something. So, maybe "v2" is enough?

2022-08-27 16:29 UTC, oliverklee commented
Indeed, the reason is that minor versions sometimes have (for us) breaking changes. So I'd like to keep `v2.4` (instead of just `v2`). We don't need the patch-level release anymore, though. I'll update the PR in a second.

2022-08-27 16:31 UTC, oliverklee commented
Done and repushed.

2022-08-27 16:37 UTC, brotkrueml requested changes

2022-08-27 16:37 UTC, brotkrueml commented on CHANGELOG.md
> +- Upgrade to Composer 2.4 (#513)
```suggestion
- Update to Composer 2.4 (#513)
```

Update -> minor/patch level version
Upgrade -> major version

2022-08-27 16:43 UTC, oliverklee commented on CHANGELOG.md
> +- Upgrade to Composer 2.4 (#513)
Done.

2022-08-27 16:47 UTC, brotkrueml approved these changes

2022-08-27 16:50 UTC, brotkrueml commented
Seems that I don't have the rights to approve it to be unblocking. The approval is only grey, not green.

2022-08-27 16:53 UTC, merged