[TASK] Explain the extension name
TYPO3-Documentation/tea pull request #741
Opened 2023-02-05 15:56 UTC by DanielSiepmann

Some might find the extension name confusing.
We therefore explain why we don't add _example or something else.

Resolves: #692

2023-02-05 15:57 UTC, DanielSiepmann commented
This is my first contribution for a very long time. Please check carefully :) E.g. do I follow our Git commit rules, etc.

2023-02-05 17:38 UTC, brotkrueml commented on Documentation/Introduction.rst
> +Why is it called tea?
```suggestion
Why is it called "tea"?
```

2023-02-05 17:38 UTC, brotkrueml commented on Documentation/Introduction.rst
> +=====================
```suggestion
=======================
```

2023-02-06 14:43 UTC, oliverklee requested changes

2023-02-06 14:43 UTC, oliverklee commented on Documentation/Introduction.rst
> +Why is it called tea?
```suggestion
Why is this extension called "tea"?
```

2023-02-06 14:43 UTC, oliverklee commented on Documentation/Introduction.rst
> +We could add ``example_`` to the name in order to state that this extension is an example.
```suggestion
We could also have added `_example` to the name in order to state that this extension is an example.
```

2023-02-08 11:15 UTC, DanielSiepmann commented
Thanks for your feedback @brotkrueml and @oliverklee I've updated the branch with your feedback.

2023-02-08 12:21 UTC, oliverklee commented on Documentation/Introduction.rst
> +We could also add `example_` to the name in order to state that this extension is an example.
```suggestion
We could also add `_example` to the name in order to state that this extension is an example.
```

2023-02-08 12:21 UTC, oliverklee approved these changes

2023-02-08 12:22 UTC, oliverklee commented
Looks good, but needs a rebase now that the other PR is merged.

2023-02-08 12:31 UTC, oliverklee approved these changes

2023-02-08 12:31 UTC, merged