Make the records localizable
TYPO3-Documentation/tea pull request #751
Opened 2023-02-21 22:17 UTC by lukaszuznanski

Resolves: #551

2023-02-22 17:26 UTC, oliverklee requested changes

2023-02-22 17:26 UTC, oliverklee commented on Configuration/TCA/tx_tea_domain_model_product_tea.php
> +                    ],
Please let's have this in one line:
```
['', 0],
```

2023-02-22 17:26 UTC, oliverklee commented on Configuration/TCA/tx_tea_domain_model_product_tea.php
> +                    . ' AND {#tx_myextension_domain_model_something}.{#sys_language_uid} IN (-1,0)',
`#tx_myextension_domain_model_something` looks like a copy'n'paste error from a template.

2023-03-01 17:30 UTC, oliverklee commented
I currently do not have a multi-language testing installation in which I could test this PR.

@brotkrueml, @DanielSiepmann Do you have a multi-language installation where you could test and review this PR?

2023-03-02 06:39 UTC, DanielSiepmann commented
> I currently do not have a multi-language testing installation in which I could test this PR.
> 
> @brotkrueml, @DanielSiepmann Do you have a multi-language installation where you could test and review this PR?

Why not add functional tests (using InternalRequest) that ensure the rendering will work? This can easily be used to make the testing instance available to the browser and manually test the backend.
Can't promise anything, but will try to add this next week if you like.

We still don't demonstrate the InternalRequest within Functional Tests anyway. So would be an additional bonus?

2023-03-21 20:10 UTC, lukaszuznanski commented
Ok so I should add tests to this PR so we can proceed.

2023-04-12 11:40 UTC, DanielSiepmann commented
I wouldn't say should. That would also only verify frontend rendering based on DB content. It wouldn't check the editing experience within Backend. Maybe we should move that to a separate issue to keep this to a minimum. I'll test your change in v11 and 12 now.

2023-04-12 12:04 UTC, DanielSiepmann commented
@lukaszuznanski I've rebased on current main and solves the TCA deprecation.
I've also tested BE and FE with v12 and v11. Looks good to me.

We don't show the language field in records, but that's not necessary anyway.

2023-05-03 11:49 UTC, oliverklee requested changes
Looks and works generally good.

Still, I think we should only make the text fields (title and description) available in the translated records, and use the image from the original record. What do you think?

2023-05-03 12:04 UTC, DanielSiepmann commented
> Still, I think we should only make the text fields (title and description) available in the translated records, and use the image from the original record. What do you think?

TYPO3 allows to have a radio to choose whether to use the one from default or a custom one. That would for example allow to use the default one in case you have a picture of the tea itself. But one could use a translated version in case the picture is the packaging with text on it and available in multiple languages?

That way we also can demonstrate that TYPO3 feature.

2023-05-03 12:09 UTC, oliverklee approved these changes

2023-05-03 12:10 UTC, oliverklee commented
> TYPO3 allows to have a radio to choose whether to use the one from default or a custom one. That would for example allow to use the default one in case you have a picture of the tea itself. But one could use a translated version in case the picture is the packaging with text on it and available in multiple languages?

Then let's have that as a separate PR.

2023-05-03 12:10 UTC, merged